# Generated by Django 5.1.3 on 2024-12-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='email')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
